name: HSD_vqd
channels:
  - conda-forge
  - defaults
  - pip:
      - absl-py==2.1.0
      - albumentations==1.3.1
      - antlr4-python3-runtime==4.9.3
      - blobfile==2.1.1
      - cachetools==5.3.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - clip==1.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - dall-e==0.1
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - filelock==3.13.1
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - ftfy==6.1.3
      - future==0.18.3
      - google-auth==2.27.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.60.1
      - idna==3.6
      - imageio==2.34.0
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - iniconfig==2.0.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lmdb==1.4.1
      - loguru==0.7.2
      - lxml==4.9.4
      - markdown==3.5.2
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - mypy==1.8.0
      - mypy-extensions==1.0.0
      - networkx==3.0
      - numpy==1.24.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python-headless==4.9.0.80
      - pillow==10.2.0
      - pluggy==1.4.0
      - protobuf==4.25.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycryptodomex==3.20.0
      - pyparsing==3.1.1
      - pytest==8.0.0
      - pytorch-fid==0.3.0
      - pytorch-gan-metrics==0.5.3
      - pytorch-lightning==1.0.8
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - qudida==0.0.4
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - timm==0.3.4
      - tomli==2.0.1
      - torch==2.1.2+cu121
      - torchaudio==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - tqdm==4.66.2
      - triton==2.1.0
      - urllib3==2.2.0
      - werkzeug==3.0.1
      - zipp==3.17.0
